version: "3.7"
services:
  sql-server-db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: nvddatabase!2022
      ACCEPT_EULA: "Y"
    volumes:
      - db-data:/var/lib/mysql/data

volumes:
  db-data:
    driver: local
    

    
   

      